name: 'Docker image Release'
description: 'Packages and releases a Docker image'

inputs:
  image:
    description: 'Docker image name to build and push'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      shell: bash
      run: |
        # Extract version from GitHub ref (e.g., refs/tags/v1.2.3 -> 1.2.3)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Using version: $VERSION"

    - name: Debug secrets
      shell: bash
      run: |
        echo "DOCKER_USER: ${DOCKER_USER:0:2}****"
        echo "DOCKER_PASSWORD: ${#DOCKER_PASSWORD} characters"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.image }}:$VERSION

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: '*.vsix'
        token: ${{ github.token }}
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        append_body: false
        replace_artifacts: true
